image: python:3.8

stages:
  - deploy

production:
  stage: deploy
  before_script:
    - pip3 install awscli --upgrade
    - pip3 install aws-sam-cli --upgrade
  script:
    - sam build
    - sam package --output-template-file packaged.yaml --s3-bucket jinixdme-gitlab-deploy
    - sam deploy --template-file packaged.yaml --stack-name sam-app --s3-bucket jinixdme-gitlab-deploy --capabilities CAPABILITY_IAM --region eu-central-1
  environment: production
